#C:\Users\bkaraca\Desktop\Redis\sentinel.conf
#Sentinel tarafından izlenecek Master sunucusu (en sonki parametre sentinel sunucu adedidir):
sentinel monitor mymaster 172.18.0.2 6379 3
 
#Master sunucunun tepki vermemesi durumunda Sentinel'in bekleme süresi:
sentinel down-after-milliseconds mymaster 5000
 
#Master sunucunun yeniden yapılandırılması için Sentinel'in beklemesi gereken süre:
sentinel failover-timeout mymaster 10000
 
#Sentinel tarafından eşzamanlı olarak kullanılacak slave sayısı:
sentinel parallel-syncs mymaster 3
